### ISSUE TITLE
iflag installation issue

### ISSUE THREAD

**Issue by dorjelemar12** [simracer-cz/iFlag#5]
Hi,
as the iFlag app is flashing Com5, at the initialization of the programm, nothing happens.
App seems to be blocked during "flashing COM5 with v0.22..." process.
Arduino IDE and NT Framework are installed 
how long should tzke the flashing process, please?
thank you!
DorjeLemar

**Comment by simracer-cz** [comment]
It shouldn't take more than a few seconds. Make sure that COM5 is really the device and eventually try to set the port of the device manually in Device Manager. Also since you have the Arduino IDE installed, go ahead and try uploading some of the example sketches (Blink is a good one - no need for extra hardware) example sketch to see if that works. Merry x-mess! :)

**Comment by dorjelemar12** [comment]
thanks for your answer but it doesn't work.
Arduino is launched on port5, and micro card type is selected.

flag is well connected via usb on pc ( and show some colors during 2 seconds as I connect it)
i strart iFlag and scan ; then it indicates "no device".

iFlag flashes com5 port and then indicates "no device", as Istart the process. iFlag logo is now blue.
and now, in device manager, the flag is in "other devices", unknown with "!" indication 
![Iflag issue](https://user-images.githubusercontent.com/76565605/103133894-8f284680-46ad-11eb-8896-0d5c655a12dc.png)
 
thanks for your help,
have a nice Christmas,

**Comment by dorjelemar12** [comment]
Hi,
here is a screenshot including Arduino IDE screen,
thanks for your help
![Iflag issue](https://user-images.githubusercontent.com/76565605/103134175-a700ca00-46af-11eb-8c41-3e1b121cfa28.png)

**Comment by simracer-cz** [comment]
Forget iFLAG now, please. Were you able to get the Arduino Blink sketch to work on your board? Also is that an genuine Arduino Uno board or some non-genuine clone? And are you sure it is an Uno board at all?

**Comment by dorjelemar12** [comment]
hi,
this is an original Arduino product.
the problem was the driver, not installed by windows.
that's why the blink test did not ran on my board.
I've launched Windows Updated and card has been recognized suddendly.
It perferctly works now!
thank you!

**Comment by simracer-cz** [comment]
Great :)
