### ISSUE TITLE
Blue flag all the time

### ISSUE THREAD

**Issue by EhsanMomeni81** [simracer-cz/iFlag#6]
First of all, thank you for a great product. I love my iFlag.

I have been using it for a while and it has worked perfectly but in the last two or three races, it's been showing "blue flag" all the time, multiple times per lap.  From lap 1 I have gotten blue flags. I have now updated to 0.89 hopefully it will solve this, but I just wanted you to let you know.

**Comment by simracer-cz** [comment]
Hi,

sorry for your issues and apologies for the inconvenience.

Please head to https://members.iracing.com/jforum/posts/list/3341549.page and in "Reporting Issues" section of the second post you will find instructions on how to download and use a diagnostic tool for iFLAG to capture video evidence. Not that I wouldn't believe you, lol, but it helps me a lot to figure out what is going on.

Cheers!

**Comment by EhsanMomeni81** [comment]
Hi,

No problem. 

⁣I download version 0.89 (I believe it's a beta) and now it works perfectly again. I'll save this mail if the issues comes back.

Thank you for a great software.

Ehsan Momeni​

Den 31 jan. 2021 07:51, kI 07:51, simracer-cz <notifications@github.com> skrev:

**Comment by simracer-cz** [comment]
Glad to be useful! :)
