### ISSUE TITLE
iFlag will not open

### ISSUE THREAD

**Issue by chrisjameschamp** [simracer-cz/iFlag#8]
Not sure why, but when I try to open iFlag, nothing happens, I have restarted, reinstalled nothing works

**Comment by chrisjameschamp** [comment]
I figured it out, you cant put iFlag in the Programs folder, it worked once I moved it to Documents

**Comment by simracer-cz** [comment]
Glad you figured it out :)

It actually is one of the primary instructions you've downloaded with the software:

> __Copy the software/iFlag folder to anywhere you like on your harddrive, except Program Files folder(s), and run it from there.__ It is useful to make a shortcut in Startup items to have iFLAG ready as soon as you start the computer.

https://github.com/simracer-cz/iFlag/tree/master/software
